version: "3.9"

services:
  build:
    image: ubuntu:22.04
    container_name: c_build
    working_dir: /workspace
    volumes:
      - ./:/workspace
    tty: true
    command: >
      bash -lc "
        apt-get update &&
        apt-get install -y build-essential cmake ninja-build &&
        rm -rf build &&
        mkdir build && cd build &&
        cmake .. -G Ninja &&
        cmake --build . -j "
     

  run_practice:
    image: ubuntu:22.04
    container_name: run_practice
    working_dir: /workspace/build/chapters/00_practice
    volumes:
      - ./:/workspace
    depends_on:
      - build
    tty: true
    command: ./practice

  run_basics:
    image: ubuntu:22.04
    container_name: run_basics
    working_dir: /workspace/build/chapters/01_basics
    volumes:
      - ./:/workspace
    depends_on:
      - build
    tty: true
    command: ./basics
